// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "PrepareShoot.h"
#include "SmartDashboard/SmartDashboard.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

PrepareShoot::PrepareShoot(): Command() {
        // Use requires() here to declare subsystem dependencies
   // Requires(Robot::shooter);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void PrepareShoot::Initialize() {
Robot::shooter->shootFront();
}

// Called repeatedly when this Command is scheduled to run
void PrepareShoot::Execute() {
	SmartDashboard::PutNumber("Shoot Velocity", Robot::shooter->getVelocity());
}

// Make this return true when this Command no longer needs to run execute()
bool PrepareShoot::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void PrepareShoot::End() {
	Robot::shooter->stopFront();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void PrepareShoot::Interrupted() {
	Robot::shooter->stopFront();
}
