// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "Modules/AHRS.h"
#include "Modules/AnalogChannelVolt.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:

	static PIDController*     driveTrainFrontLeft;
		static SpeedController*   driveTrainFrontLeftDrive;
		static AnalogChannelVolt* driveTrainFrontLeftPos;
		static SpeedController*   driveTrainFrontLeftSteer;

	    static PIDController*     driveTrainFrontRight;
		static SpeedController*   driveTrainFrontRightDrive;
		static AnalogChannelVolt* driveTrainFrontRightPos;
		static SpeedController*   driveTrainFrontRightSteer;

		static PIDController*     driveTrainRearLeft;
		static SpeedController*   driveTrainRearLeftDrive;
		static AnalogChannelVolt* driveTrainRearLeftPos;
		static SpeedController*   driveTrainRearLeftSteer;

		static PIDController*     driveTrainRearRight;
		static SpeedController*   driveTrainRearRightDrive;
		static AnalogChannelVolt* driveTrainRearRightPos;
		static SpeedController*   driveTrainRearRightSteer;

		static I2C* i2c;

		static AHRS* imu;

		static SerialPort* serialPort;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<SpeedController> leftFront;
	static std::shared_ptr<SpeedController> rightRear;
	static std::shared_ptr<SpeedController> rightFront;
	static std::shared_ptr<SpeedController> leftRear;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
